spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    
    name: pingbanche-config-dev
---
spring:
  profiles: test   
  application:
    name: pingbanche-config-dev

